### ISSUE TITLE
NoMethodError when using summary metric without labels

### ISSUE THREAD

**Issue by siebertm** [discourse/prometheus_exporter#7]
When I observe a `PrometheusExporter::Metric::Summary` without passing any label, I get a `NoMethodError: undefined method `merge' for nil:NilClass` when scraping the metrics

```
[2018-02-16 09:12:59] ERROR NoMethodError: undefined method `merge' for nil:NilClass
        /home/siebert/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/prometheus_exporter-0.1.13/lib/prometheus_exporter/metric/summary.rb:57:in `block (2 levels) in metric_text'
        /home/siebert/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/prometheus_exporter-0.1.13/lib/prometheus_exporter/metric/summary.rb:56:in `each'
        /home/siebert/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/prometheus_exporter-0.1.13/lib/prometheus_exporter/metric/summary.rb:56:in `block in metric_text'
        /home/siebert/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/prometheus_exporter-0.1.13/lib/prometheus_exporter/metric/summary.rb:53:in `each'
        /home/siebert/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/prometheus_exporter-0.1.13/lib/prometheus_exporter/metric/summary.rb:53:in `metric_text'
        /home/siebert/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/prometheus_exporter-0.1.13/lib/prometheus_exporter/metric/base.rb:61:in `to_prometheus_text'
        /home/siebert/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/prometheus_exporter-0.1.13/lib/prometheus_exporter/server/collector.rb:55:in `map'
        /home/siebert/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/prometheus_exporter-0.1.13/lib/prometheus_exporter/server/collector.rb:55:in `block in prometheus_metrics_text'
        /home/siebert/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/prometheus_exporter-0.1.13/lib/prometheus_exporter/server/collector.rb:53:in `synchronize'
        /home/siebert/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/prometheus_exporter-0.1.13/lib/prometheus_exporter/server/collector.rb:53:in `prometheus_metrics_text'
        /home/siebert/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/prometheus_exporter-0.1.13/lib/prometheus_exporter/server/web_server.rb:117:in `block in metrics'
        /home/siebert/.rbenv/versions/2.3.1/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
        /home/siebert/.rbenv/versions/2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
        /home/siebert/.rbenv/versions/2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `catch'
        /home/siebert/.rbenv/versions/2.3.1/lib/ruby/2.3.0/timeout.rb:33:in `catch'
        /home/siebert/.rbenv/versions/2.3.1/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
        /home/siebert/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/prometheus_exporter-0.1.13/lib/prometheus_exporter/server/web_server.rb:116:in `metrics'
        /home/siebert/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/prometheus_exporter-0.1.13/lib/prometheus_exporter/server/web_server.rb:54:in `block in initialize'
        /home/siebert/.rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/httpservlet/prochandler.rb:39:in `do_GET'
        /home/siebert/.rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/httpservlet/abstract.rb:107:in `service'
        /home/siebert/.rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
        /home/siebert/.rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
        /home/siebert/.rbenv/versions/2.3.1/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
::1 - - [16/Feb/2018:09:12:59 CET] "GET /metrics HTTP/1.1" 500 321
```

When I `observe` passing labels, everything works fine!

**Comment by SamSaffron** [comment]
ok should be fixed and released!
