### ISSUE TITLE
Rails Errno::EADDRINUSE: Address already in use - bind(2) for 0.0.0.0:12345

### ISSUE THREAD

**Issue by mariokam** [discourse/prometheus_exporter#73]
The **problem** I am having is that I am not able to run the Prometheus exporter in single process model.
The way I am doing it is by running **command**:
`rake db:schema:cache:dump && exec env WEB_CONCURRENCY=1 MAX_THREADS=1 BUNDLE_DISABLE_EXEC_LOAD=true PGBOUNCER_USE_FOR_PROC=1 bundle exec puma -C config/puma.rb`

which results:
```
rake aborted!
Errno::EADDRINUSE: Address already in use - bind(2) for 0.0.0.0:12345
<path>/config/initializers/prometheus_exporter.rb:11:in `new'
<path>/config/initializers/prometheus_exporter.rb:11:in `<top (required)>'
<path>/config/environment.rb:5:in `<top (required)>'
Tasks: TOP => db:schema:cache:dump => db:load_config => environment
(See full trace by running task with --trace)

```

my `initializers/prometheus_exporter.rb` looks like this:
```
unless Rails.env.test?

  require 'prometheus_exporter/server'

  # client allows instrumentation to send info to server
  require 'prometheus_exporter/client'
  require 'prometheus_exporter/instrumentation'

  # port is the port that will provide the /metrics route
  server = PrometheusExporter::Server::WebServer.new port: 12345
  server.start

  # wire up a default local client
  PrometheusExporter::Client.default = PrometheusExporter::LocalClient.new(collector: server.collector)

  # this ensures basic process instrumentation metrics are added such as RSS and Ruby metrics
  PrometheusExporter::Instrumentation::Process.start(type: 'master')

  gauge = PrometheusExporter::Metric::Gauge.new('rss', 'used RSS for process')
  counter = PrometheusExporter::Metric::Counter.new('web_requests', 'number of web requests')
  summary = PrometheusExporter::Metric::Summary.new('page_load_time', 'time it took to load page')
  histogram = PrometheusExporter::Metric::Histogram.new('api_access_time', 'time it took to call api')

  server.collector.register_metric(gauge)
  server.collector.register_metric(counter)
  server.collector.register_metric(summary)
  server.collector.register_metric(histogram)

  gauge.observe(get_rss)
  gauge.observe(get_rss)

  counter.observe(1, route: 'test/route')
  counter.observe(1, route: 'another/route')

  summary.observe(1.1)
  summary.observe(1.12)
  summary.observe(0.12)

  histogram.observe(0.2, api: 'twitter')

  # http://localhost:12345/metrics now returns all your metrics
end
```

any idea?

**Comment by SamSaffron** [comment]
The error message is a strong indicator that either: 

```

  # port is the port that will provide the /metrics route
  server = PrometheusExporter::Server::WebServer.new port: 12345
  server.start
```

This is called twice or somehow another process is running that.

**Comment by mariokam** [comment]
Probably it has what to do with puma in clustered mode and not clustered puma, because each puma worker theoretically starts the whole rails from the scratch, with that I guess it starts server multiple times on same port, but as you can see I run single worker puma and still the same ...

**Comment by discordianfish** [comment]
Well if you have your rails app already running und then run a rails command, the initializer runs as well trying to bind the port that is already used. I am too looking for a way to ensure the exporter server is only run when runnning the rails server. Any ideas?
